### ISSUE TITLE
Some functions' API are missing?

### ISSUE THREAD

**Issue by Blumenkranz** [trixi-framework/P4est.jl#102]
It seems that we don't have the API for functions like `p4est_quadrant_sibling`. 
See https://github.com/cburstedde/p4est/blob/aafb87d93e33dffe24d67533d56bc2f0cdb72605/src/p4est_bits.c#L1250
I'm not sure if this is normal.

**Comment by JoshuaLampert** [comment]
We don't wrap all of the headers provided by `p4est`. Currently, we generate bindings for
https://github.com/trixi-framework/P4est.jl/blob/62a86e05002e23ec1330a36be3a0bbcae73906a9/dev/generator.jl#L31-L33
and their dependent headers, which are
```julia
p4est_connectivity.h
sc_io.h
sc.h
sc_config.h
sc_mpi.h
sc_containers.h
p4est_base.h
p4est_config.h
p4est_mesh.h
p4est_ghost.h
p4est_iterate.h
p4est_lnodes.h
p8est_connectivity.h
p8est_mesh.h
p8est_ghost.h
p8est_iterate.h
p8est_lnodes.h
sc_uint128.h
```
i.e. `p4est_bits.h` is not part of that. See also one of the items [here](https://github.com/trixi-framework/P4est.jl/issues/54#issue-1498187348).

**Comment by Blumenkranz** [comment]
I see. I will try to access them by myself. Thanks!

**Comment by JoshuaLampert** [comment]
You could also clone P4est.jl, add "p4est_bits.h" to the list of headers in [dev/generator.jl](https://github.com/trixi-framework/P4est.jl/blob/main/dev/generator.jl#L31) I linked above, create the LibP4est.jl file as described in the [dev/README](https://github.com/trixi-framework/P4est.jl/tree/main/dev#building-julia-bindings-of-p4est-with-clangjl), copy the new LibP4est.jl into `src/` and use a dev'ed P4est.jl version.

**Comment by Blumenkranz** [comment]
Great advice. Thanks again!
