### ISSUE TITLE
Compile p4est in P4est_jll.jl with MPI support

### ISSUE THREAD

**Issue by sloede** [trixi-framework/P4est.jl#4]
Right now, p4est in `P4est_jll.jl` is compiled without MPI support:
https://github.com/JuliaPackaging/Yggdrasil/blob/999e6cf6b9054a05a4e76a1d23de93c5651396a2/P/P4est/build_tarballs.jl#L21

Let's try to fix that by compiling against `MPICH_jll` on Linux/MacOS/FreeBSD and `MicrosoftMPI_jll` on Windows.

Blocked by #5 since before we enable MPI support, we should have the ability to switch out the p4est backend provided via P4est_jll.jl against a system-installed library. Otherwise, P4est.jl will not even work on systems that switch out the MPI backend in MPI.jl, even if we are not using p4est in parallel.

**Comment by lchristm** [comment]
Closing this since it's done now. See https://github.com/JuliaPackaging/Yggdrasil/pull/4324 and #45.
